### ISSUE TITLE
Developer workflow and conventions

### ISSUE THREAD

**Issue by alessandrofelder** [Yanlan-Mao-Lab/TissueOrigami#18]
To discuss on Friday and document.

We should agree on a convention about how many approvals are needed for a PR to be merged. I'd default to 1. So in our team of three, if person A submits a PR and either person B or C approves it, it can be merged. But sometimes I expect we have a reason for wanting someone specific, or both other people, to review.

We should also agree on whether the reviewer or the assignee of a merge request merges.

**Comment by willGraham01** [comment]
Closed upon merging of #23
