### ISSUE TITLE
UI: Additional Element Properties to Display

### ISSUE THREAD

**Issue by willGraham01** [Yanlan-Mao-Lab/TissueOrigami#41]
Depends on #39 |

At present, the dropdown menu for selecting element properties to be displayed only allows the user to choose between Growth and GrowthRate. 

We require a list of the additional (element-wise) properties that we want to add to the selection, and then to add these options to the possible selection. @nkhalilgharibi if you have certain properties in mind, please feel free to add them in a comment below.

Additional Physical Properties:
- [x] External Viscosity (this is node, rather than element, based). This has been moved to #50.
- [x] Internal Viscosity
- [x] Young Modulus
- [x] Poisson Ratio
- [x] Volume (xyz) Growth Rate
- [x] Volume Growth
- [x] Emergent Size & Shape
- [x] ShapeChangeRate_z

Additional Strain Properties
- [x] Volumetric Strain (via Fe)
- [x] Strain in DV
- [x] Strain in AP
- [x] Strain in AB
- [x] Shear in xy
- [x] Shear in xz
- [x] Shear in yz

**Comment by nkhalilgharibi** [comment]
Properties which would be useful to have:
- All properties from the "Physical Properties" drop-down menu (especially external/internal viscosity, Youngs modulus, Poisson ratio, volume growth rate, shapeChangeRate_z)
- all properties from the "Strain" drop-down menu

**Comment by nkhalilgharibi** [comment]
It would also be useful to be able to export the coordinates of the 6 nodes of the element.

**Comment by nkhalilgharibi** [comment]
Also, as discussed yesterday, would be good to have the option to do this for one element, list of elements, elements from a specific tissue type, all elements.

**Comment by willGraham01** [comment]
> It would also be useful to be able to export the coordinates of the 6 nodes of the element.
> Also, as discussed yesterday, would be good to have the option to do this for one element, list of elements, elements from a specific tissue type, all elements.

No problem - I'm going to break these two out into separate issues, as they can likely be worked on independently from each other.
