### ISSUE TITLE
Simulation/UI: Possible `getStrain` error

### ISSUE THREAD

**Issue by willGraham01** [Yanlan-Mao-Lab/TissueOrigami#52]
Whilst writing the GUI displays for the additional physical properties (see #41), it was noticed that the `getStrain` method of `ShapeBase` appears to have a redundant `else if` statement.

Examining the [`getStrain`](https://github.com/Yanlan-Mao-Lab/TissueOrigami/blob/ca6a4cc9bb106356e0434879b3071d8ca14c2b03/TissueFolding/SourceCode/ShapeBase.cpp#L1225-L1264) function for use in displaying the properties of a selected element, one will notice the `else if` statement of [line 1258](https://github.com/Yanlan-Mao-Lab/TissueOrigami/blob/ca6a4cc9bb106356e0434879b3071d8ca14c2b03/TissueFolding/SourceCode/ShapeBase.cpp#L1258) repeats the condition of [line 1246](https://github.com/Yanlan-Mao-Lab/TissueOrigami/blob/ca6a4cc9bb106356e0434879b3071d8ca14c2b03/TissueFolding/SourceCode/ShapeBase.cpp#L1246), and is thus never executed. This is irregular given that this function is only meant to be accessing the `xy` `Shear` value, and this convention appears to forbid any access to the `xy` component of `Shear` (and worse, return a _the wrong_ value, rather than erroring!).

The format of this function suggest that [line 1258](https://github.com/Yanlan-Mao-Lab/TissueOrigami/blob/ca6a4cc9bb106356e0434879b3071d8ca14c2b03/TissueFolding/SourceCode/ShapeBase.cpp#L1258) should read
```c++
else if (type === 6)
```
This is further reinforced by the fact that the conditional block that follows is different to the previous (and follows a similar convention to the else-if statements. If the suggested change is to be made, one can also tidy up the `getStrain` function into the following:
```c++
void ShapeBase::getStrain(int type, float &StrainMag){
	StrainMag = 0.0;
	if (type == 0){
		//This is volumetric strain, the total volume change:
		gsl_matrix* Fe = getFe();
		StrainMag = determinant3by3Matrix(Fe)-1 ;
		gsl_matrix_free(Fe);
	}
        // If type>0, then accessing occurs in the same manner for each component.
        // Listed are the type : component pairings
        // DV : 1, AP : 2, AB : 3, xy : 4, yz : 5, xz : 6
        else if (0<type && type<7) {
                // indexing induces -1 offset to type
                StrainMag = gsl_matrix_get(Strain, type-1, 0);
        }
        else {
                return;
        }
}
```

*NOTE:* There are other concerns with this function (like the potential to `return` without assigning a value to `StrainMag`) which might also need addressing in a more detailed, context-specific code review.

**Comment by nkhalilgharibi** [comment]
Yes, I think this was a typo. I like the tidied-up version. Please modify the code as you suggest.
